{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akri-spore-controller-sa
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-spore-controller
    app.kubernetes.io/component: spore-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akri-driver-controller-sa
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-driver-controller
    app.kubernetes.io/component: driver-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akri-agent-sa
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-agent
    app.kubernetes.io/component: agent
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "akri-spore-controller-role"
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-spore-controller
    app.kubernetes.io/component: spore-controller
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [{{ .Values.crds.group | quote }}]
  resources: ["instances", "spores"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [{{ .Values.crds.group | quote }}]
  resources: ["configurations"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "akri-driver-controller-role"
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-driver-controller
    app.kubernetes.io/component: driver-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclasses", "podschedulingcontexts"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["resource.k8s.io"]
  resources: ["podschedulingcontexts/status", "resourceclaims", "resourceclaims/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [{{ .Values.crds.group | quote }}]
  resources: ["instances", "spores"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [{{ .Values.crds.group | quote }}]
  resources: ["discoveryconfigurations", "instancefilters"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "akri-agent-role"
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-agent
    app.kubernetes.io/component: agent
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [{{ .Values.crds.group | quote }}]
  resources: ["instances"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [{{ .Values.crds.group | quote }}]
  resources: ["discoveryconfigurations"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: 'rbac.authorization.k8s.io/v1'
kind: 'ClusterRoleBinding'
metadata:
  name: 'akri-spore-controller-binding'
  namespace: {{ .Release.Namespace }}
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-spore-controller
    app.kubernetes.io/component: spore-controller
roleRef:
  apiGroup: ''
  kind: 'ClusterRole'
  name: 'akri-spore-controller-role'
subjects:
  - kind: 'ServiceAccount'
    name: 'akri-spore-controller-sa'
    namespace: {{ .Release.Namespace }}
---
apiVersion: 'rbac.authorization.k8s.io/v1'
kind: 'ClusterRoleBinding'
metadata:
  name: 'akri-driver-controller-binding'
  namespace: {{ .Release.Namespace }}
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-driver-controller
    app.kubernetes.io/component: driver-controller
roleRef:
  apiGroup: ''
  kind: 'ClusterRole'
  name: 'akri-driver-controller-role'
subjects:
  - kind: 'ServiceAccount'
    name: 'akri-driver-controller-sa'
    namespace: {{ .Release.Namespace }}
---
apiVersion: 'rbac.authorization.k8s.io/v1'
kind: 'ClusterRoleBinding'
metadata:
  name: 'akri-agent-binding'
  namespace: {{ .Release.Namespace }}
  labels: {{- include "akri.labels" . | nindent 4 }}
    app.kubernetes.io/name: akri-agent
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: ''
  kind: 'ClusterRole'
  name: 'akri-agent-role'
subjects:
  - kind: 'ServiceAccount'
    name: 'akri-agent-sa'
    namespace: {{ .Release.Namespace }}
{{- end }}